### PR TITLE
feat: Initial K8s Manifest

### LINKED ISSUE #204: Kubernetes Manifest
I'm about to convert the compose files to kubernetes manifests. 
Deploying a K8s Environment is as easy as starting docker nowadays.

Any suggsetion on the folder structure? Where can i push the .yaml files to?

thanks

### PR DESCRIPTION
**Pull request by Berndinox**
Initial Commit of Kubernetes Manifest!
_It's working on my K8s Cluster.. :)_

**Ingress**: SSL offload works fine, MELI_URL should still start with "https"
HTTPProxy requires: [Project Contour](https://projectcontour.io/)

**Todo**: livenessProbe & readinessProbe for Meli

**Recommendation**: 

- make Dockferfile "non-root", then we could run the container as "1001".
- MELI_MONGO_URI should be built at runtime with e.g. a bash script. Then we could pass mongo password as a Secret from another ENV Var

### CODE REVIEW

**Comment by Berndinox** [comment]
Reference: https://github.com/getmeli/meli/issues/204

**Comment by Berndinox** [comment]
Seems like Contour is no good choice, because there is no wildcard fqdn support (yet)
https://github.com/projectcontour/contour/pull/3381

**Comment by gempain** [comment]
@Berndinox this is awesome 😀  I'm actually far from being a K8S expert so I won't be of great help here. I was worried you'd have issues with SSL configuration. Wildcard certificates are an issue ATM. That said, know that branch domains will be moved to the top level because right now, you need wildcard certificates for both site main branches and site branches. We're aiming to have something like `site.mymeli.com` and `site-branch.mymeli.com` or something similar and this should be coming in the next few beta releases.

**Comment by Berndinox** [comment]
When using K8s you basicly disable all cert stuff inside meli and use SSL Offload on the Ingress-Controller in front of. 
Using site-branch.mymeli.com is way better because Wildcard Certificates for sub.sub Domains is hard...

**Comment by gempain** [comment]
Yup, we'll be removing that sub.sub thing, it makes things a bit more difficult in the code too. All branches will be released under the same subdomain.

**Comment by gempain** [comment]
@Berndinox just let me know when you want us to merge this 😄

**Comment by Berndinox** [comment]
LGTM - should be good enough for a first merge.
I will come up with some finetuning soon... ;)

**Comment by gempain** [comment]
Awesome ! I'll merge then. You're welcome to open a new one for fine tunes !

**Comment by gempain** [comment]
@Berndinox thanks so much for this, it was a big missing piece for us, and we're glad to have it now 😄

**Pull request merged**
