### PR TITLE
feat(ui): Improve toast error messages

### LINKED ISSUE #244: Better diagnostics and/or default for MELI_MAX_ORGS
I installed `meli` using in-memory auth.  I created an org and everything worked great.  Then I decided to implement our SSO system based on Gitlab.  I eventually got that working as well.  But when I logged in via Gitlab and tried to create an organization, I couldn't.  The error message was just a `403` + `could not create org`.  The "could not create org" is coming [from the client side](https://github.com/getmeli/meli/blob/b045ce50d944320d515b3193340786f0fc8f129c/ui/src/components/orgs/AddOrg.tsx#L38).  But the server is actually returning "Cannot create more orgs" in its response.  It seems the client just fails to read the message provided by the server and render it in the UI.

So I looked at the code and specifically the tests to see when a `403` would appear and it was because the limit on organizations had been reached.  So then I looked for the default and found that it was just one.  I changed my deployment to use a larger number and everything is fine.

So I have a few suggestions to avoid this confusion in the future.  The first is that you are producing a response in the `403` that includes an error message so the UI should actually render that message.  This provides the user with something actionable to address.  I also wonder why the default maximum for organizations is one?  It is true that I'll probably only use one, but it seems like multiple people might fall into this trap when switching authentication schemes because if I log in via "in memory" I see one set of organizations and if I log in via Gitlab I see an entirely different and mutually exclusive set of organizations.  I can imagine other users getting caught in this if they decide to switch authentication methods and a) suddenly all their existing orgs disappear and b) they can't actually see (even if they are using the in-memory credentials which seems like a "root" account) all the organizations so they can't know whether they are exceeding the limit.

I'm curious, is there a reason why the default org limit is only 1?  Without a diagnostic message that clearly states why the organization creation failed, I could see many users trying to create their second organization and scratching their head as to why that should fail when they managed to create a previous one just fine.

Anyway, just some suggestions to smooth the onboarding process for new users.  Getting into the plumbing of how you client does error handling is a bit much for me to bite off with a PR to fix the error handling.  But a simple solution might be to just raise the org limit so people are less likely to bump into this issue.

### PR DESCRIPTION
**Pull request by mtiller**
This just modified the error handling on several `axios` calls
to extract the underlying error embedded in the HTTP response
so it is visible to the user.

Sorry for all the changes.  The only real changes here are to the 
`toast` calls.  It appears that this project doesn't include
a `.prettierrc` file to standardize `prettier` settings.  As s result, you'll
end up with this situation where all the files get formatted according
to different settings.  You might want to consider adding a `.prettierrc`
file to ensure consistent formatting (at least among VS Code users).

This closes #244

### CODE REVIEW

**Comment by gempain** [comment]
Thanks so much for the changes ! Is there a way to rollback the changes made by prettier ? I would happily add a prettier config and also use it across the app, but I'd do this in another MR to avoid mixing things. Would you be able to configure a `.prettierrc` to automatically rollback the formatting changes ? If it's not possible I'll go through the review but there's indeed quite a lot of changes 😄

**Comment by mtiller** [comment]
The problem is that I don't know what that `.prettierrc` should look like.  I don't know what settings were used by all the contributors to `meli`.  If we had such a `.prettierrc` file, all I'd need to do is resave all these files and push one more commit to the end of this branch.  Do you know what editor was used for this and what formatting standards were followed?

**Comment by mtiller** [comment]
I'll resubmit this without all the formatting changes.  Just ignore this PR.  I'll make a fresh one.

**Comment by gempain** [comment]
@mtiller don't worry I can still review 😄  Regarding the prettier file to use, all I ask for is:
- 2 spaces indentation
- single quotes
I can setup a `.prettierrc` and provide it to you. Just need a bit of time.

**Comment by mtiller** [comment]
There is now a much cleaner PR, #253.

**Pull request closed without merging**
